default: &default
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/influxdata-operator

version: 2

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - gopkg-v1-{{ checksum "Gopkg.lock" }}
      - run: make dep
      - run:
          name: Install operator-sdk
          command: |
            export RELEASE_VERSION=v0.8.1
            curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu \
              && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk \
              && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
      - save_cache:
          key: gopkg-v1-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make build orgname=orangesys

